name: Basic Docker build

on: 
  push:
    tags: 
      - '*'

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: docker.io

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      
      - name: List all files
        run: ls -la

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Logging Logs logs
        shell: bash
        run: |
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          echo ${{ steps.meta.outputs.tags }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}



          
          
